// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-WaQaDO-XaFU7Cge2llieingQoWEQK8o',
    appId: '1:730049145736:web:1eb142fe7ba3bc34cce83d',
    messagingSenderId: '730049145736',
    projectId: 'subscription-box-app-9ad03',
    authDomain: 'subscription-box-app-9ad03.firebaseapp.com',
    storageBucket: 'subscription-box-app-9ad03.firebasestorage.app',
    measurementId: 'G-2XDK4J5C90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaaB3pxlZ5yxfU7ZGDhd86cLTMOJx_oWM',
    appId: '1:730049145736:android:22a5031b5257595bcce83d',
    messagingSenderId: '730049145736',
    projectId: 'subscription-box-app-9ad03',
    storageBucket: 'subscription-box-app-9ad03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQz59kK213-uwX03R2Fz9LubHUyH9xDcU',
    appId: '1:730049145736:ios:b638aca2a34f34efcce83d',
    messagingSenderId: '730049145736',
    projectId: 'subscription-box-app-9ad03',
    storageBucket: 'subscription-box-app-9ad03.firebasestorage.app',
    iosBundleId: 'com.example.subboxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQz59kK213-uwX03R2Fz9LubHUyH9xDcU',
    appId: '1:730049145736:ios:b638aca2a34f34efcce83d',
    messagingSenderId: '730049145736',
    projectId: 'subscription-box-app-9ad03',
    storageBucket: 'subscription-box-app-9ad03.firebasestorage.app',
    iosBundleId: 'com.example.subboxApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-WaQaDO-XaFU7Cge2llieingQoWEQK8o',
    appId: '1:730049145736:web:e2fe1ce07256d8abcce83d',
    messagingSenderId: '730049145736',
    projectId: 'subscription-box-app-9ad03',
    authDomain: 'subscription-box-app-9ad03.firebaseapp.com',
    storageBucket: 'subscription-box-app-9ad03.firebasestorage.app',
    measurementId: 'G-3T68E50RXW',
  );
}
